/*global Item */
/*jslint devel: true */
/*jslint white: true */

var PRODUCTS = {"repo": [{
                    'eventPosition': 1,
                    'eventProductId': '282555',
                    'eventProductName': 'флешка 16ГБ Kingston DataTraveler SE9',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '560.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 2,
                    'eventProductId': '422360',
                    'eventProductName': 'флешка 8ГБ Smart Buy Glossy',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '330.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 3,
                    'eventProductId': '3867712',
                    'eventProductName': 'флешка 32ГБ Smart Buy Glossy, SB32GBGS-K',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '640.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 4,
                    'eventProductId': '4068304',
                    'eventProductName': 'флешка 16ГБ Smart Buy Glossy, SB16GBGS-B',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '470.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 5,
                    'eventProductId': '386725',
                    'eventProductName': 'флешка 32ГБ Kingston DataTraveler SE9',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1020.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 6,
                    'eventProductId': '3961417',
                    'eventProductName': 'флешка 32ГБ SanDisk Ultra Dual 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023890',
                    'eventCategoryName': 'Двойной USB-разъем',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1060.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 7,
                    'eventProductId': '3823977',
                    'eventProductName': 'флешка 8ГБ Smart Buy LARA',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '410.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 8,
                    'eventProductId': '3964834',
                    'eventProductName': 'флешка 16ГБ SanDisk Cruzer Ultra Fit, USB 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '590.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 9,
                    'eventProductId': '198302',
                    'eventProductName': 'флешка 8ГБ SanDisk Cruzer Blade',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '480.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 10,
                    'eventProductId': '227084',
                    'eventProductName': 'флешка 16ГБ Transcend JetFlash 700',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '720.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 11,
                    'eventProductId': '3964836',
                    'eventProductName': 'флешка 32ГБ SanDisk Cruzer Ultra Fit, USB 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1060.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 12,
                    'eventProductId': '534291',
                    'eventProductName': 'флешка 16ГБ SanDisk Ultra, USB 3.0, SDCZ48-016G-U46',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '580.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 13,
                    'eventProductId': '422263',
                    'eventProductName': 'флешка 8ГБ Smart Buy Glossy',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '370.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 14,
                    'eventProductId': '3823983',
                    'eventProductName': 'флешка 16ГБ Smart Buy LARA',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '500.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 15,
                    'eventProductId': '282553',
                    'eventProductName': 'флешка 8ГБ Kingston DataTraveler SE9',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '530.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 16,
                    'eventProductId': '3867700',
                    'eventProductName': 'флешка 16ГБ Smart Buy Glossy, SB16GBGS-K',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '440.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 17,
                    'eventProductId': '534298',
                    'eventProductName': 'флешка 32ГБ SanDisk Ultra, USB 3.0, SDCZ48-032G-U46',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1060.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 18,
                    'eventProductId': '3964848',
                    'eventProductName': 'флешка 64ГБ SanDisk Cruzer Ultra Fit, USB 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1620.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 19,
                    'eventProductId': '3823980',
                    'eventProductName': 'флешка 32ГБ Smart Buy LARA',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Smart Buy',
                'eventProductPrice': '870.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 20,
                    'eventProductId': '280719',
                    'eventProductName': 'флешка 16ГБ Transcend JetFlash 350',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '620.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 21,
                    'eventProductId': '386730',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler SE9',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1740.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 22,
                    'eventProductId': '890614',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler microDuo 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023890',
                    'eventCategoryName': 'Двойной USB-разъем',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1790.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 23,
                    'eventProductId': '3465516',
                    'eventProductName': 'флешка 16ГБ Kingston DataTraveler 100 G3',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '540.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 24,
                    'eventProductId': '3410089',
                    'eventProductName': 'флешка 32ГБ Kingston DataTraveler SE9 G2 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1110.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 25,
                    'eventProductId': '932213',
                    'eventProductName': 'флешка 16ГБ Transcend JetFlash 710',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '960.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 26,
                    'eventProductId': '165750',
                    'eventProductName': 'флешка 16ГБ Silicon Power I-Series',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Silicon Power',
                'eventProductPrice': '570.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 27,
                    'eventProductId': '3410093',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler SE9 G2 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1830.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 28,
                    'eventProductId': '930674',
                    'eventProductName': 'флешка 64ГБ Transcend JetFlash 710',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '2270.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 29,
                    'eventProductId': '200616',
                    'eventProductName': 'флешка 8ГБ Kingston DataTraveler 101 G2',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '440.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 30,
                    'eventProductId': '3696055',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler Micro 3.1',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1830.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 31,
                    'eventProductId': '3696078',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler microDuo 3C',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023890',
                    'eventCategoryName': 'Двойной USB-разъем',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1850.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 32,
                    'eventProductId': '193971',
                    'eventProductName': 'флешка 16ГБ Silicon Power I-Series',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Silicon Power',
                'eventProductPrice': '560.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 33,
                    'eventProductId': '232061',
                    'eventProductName': 'флешка 8ГБ Silicon Power Touch 830, SP008GBUF2830V2S',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Silicon Power',
                'eventProductPrice': '510.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 34,
                    'eventProductId': '441800',
                    'eventProductName': 'флешка 64ГБ Transcend JetFlash 780',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '3820.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 35,
                    'eventProductId': '3937419',
                    'eventProductName': 'флешка 64ГБ PhotоFast PhotoBackup Cable 1m, PBCU364GB',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'PhotoFast',
                'eventProductPrice': '5200.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 36,
                    'eventProductId': '264782',
                    'eventProductName': 'флешка 16ГБ Silicon Power Touch T01',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Silicon Power',
                'eventProductPrice': '670.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 37,
                    'eventProductId': '3937424',
                    'eventProductName': 'флешка 32ГБ PhotоFast PhotoBackup Cable 1m, PBCU332GB',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'PhotoFast',
                'eventProductPrice': '3950.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 38,
                    'eventProductId': '698565',
                    'eventProductName': 'флешка 16ГБ Kingston DataTraveler G4',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '580.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 39,
                    'eventProductId': '478376',
                    'eventProductName': 'флешка 32ГБ Kingston DataTraveler 100 G3',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1040.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 40,
                    'eventProductId': '621936',
                    'eventProductName': 'флешка 16ГБ SanDisk Extreme',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1610.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 41,
                    'eventProductId': '698596',
                    'eventProductName': 'флешка 32ГБ Kingston DataTraveler G4',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1040.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 42,
                    'eventProductId': '3505848',
                    'eventProductName': 'флешка 128ГБ Leef iBRIDGE, Lightning',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Leef',
                'eventProductPrice': '16470.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 43,
                    'eventProductId': '3937398',
                    'eventProductName': 'флешка 128ГБ PhotоFast MemoriesCable G3, MCG3U3BK128GB',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'PhotoFast',
                'eventProductPrice': '9770.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 44,
                    'eventProductId': '928487',
                    'eventProductName': 'флешка 64ГБ Transcend JetFlash 820G',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '2460.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 45,
                    'eventProductId': '478370',
                    'eventProductName': 'флешка 64ГБ Kingston DataTraveler 100 G3',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1770.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 46,
                    'eventProductId': '889680',
                    'eventProductName': 'флешка 32ГБ Kingston DataTraveler microDuo 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023890',
                    'eventCategoryName': 'Двойной USB-разъем',
                    'eventVendorName': 'Kingston',
                'eventProductPrice': '1240.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 47,
                    'eventProductId': '3873292',
                    'eventProductName': 'флешка 32ГБ Transcend JetDrive Go 500, TS32GJDG500G, Lightning, USB 3.1, flash usb, золотая',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '5010.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 48,
                    'eventProductId': '3713670',
                    'eventProductName': 'флешка 32ГБ Leef iBRIDGE, Lightning',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Leef',
                'eventProductPrice': '6220.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 49,
                    'eventProductId': '932410',
                    'eventProductName': 'флешка 16ГБ Transcend JetFlash 750',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '1010.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 50,
                    'eventProductId': '3713673',
                    'eventProductName': 'флешка 128ГБ Leef iBRIDGE, Lightning',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Leef',
                'eventProductPrice': '15680.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 51,
                    'eventProductId': '3794143',
                    'eventProductName': 'флешка 32ГБ Transcend JetDrive Go 300, TS32GJDG300K, Lightning, USB 3.1, flash usb, черная',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '4620.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 52,
                    'eventProductId': '3794136',
                    'eventProductName': 'флешка 32ГБ Transcend JetDrive Go 300, TS32GJDG300S, Lightning, USB 3.1, flash usb, серебристая',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '4620.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 53,
                    'eventProductId': '3794266',
                    'eventProductName': 'флешка 256ГБ Leef iBRIDGE, Lightning',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Leef',
                'eventProductPrice': '34980.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 54,
                    'eventProductId': '3551793',
                    'eventProductName': 'флешка 32ГБ Adenovo U-Drive',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Adenovo',
                'eventProductPrice': '5160.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 55,
                    'eventProductId': '953323',
                    'eventProductName': 'флешка 32ГБ iStick, белая',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'iStick',
                'eventProductPrice': '6100.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 56,
                    'eventProductId': '3713668',
                    'eventProductName': 'флешка 16ГБ Leef iBRIDGE, Lightning',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15023891',
                    'eventCategoryName': 'Для Apple',
                    'eventVendorName': 'Leef',
                'eventProductPrice': '5590.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 57,
                    'eventProductId': '239660',
                    'eventProductName': 'флешка 32ГБ Transcend JetFlash 700',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'Transcend',
                'eventProductPrice': '1120.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 58,
                    'eventProductId': '3685410',
                    'eventProductName': 'флешка 64ГБ SanDisk Cruzer Ultra Flair, USB 3.0',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '1690.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 59,
                    'eventProductId': '3685373',
                    'eventProductName': 'флешка 128ГБ SanDisk Ultra, USB 3.0, SDCZ48-128G-U46',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '3050.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                },{
                    'eventPosition': 60,
                    'eventProductId': '198301',
                    'eventProductName': 'флешка 16ГБ SanDisk Cruzer Blade',
                    'eventProductTag': 'none',
                    'eventCategoryId': '15006858',
                    'eventCategoryName': 'Обычная',
                    'eventVendorName': 'SanDisk',
                'eventProductPrice': '520.00',
                'eventBlockVendor': 'Ulmart',
                'eventPromoStrategy': '',
                'eventLocation': 'MainCatalog'
                }]};
